name: color_memorizer
description: "A Flutter project for the Color Memory Game"
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  firebase_core: ^2.27.0
  firebase_auth: ^4.17.8
  cloud_firestore: ^4.15.8
  provider: ^6.1.1
  shared_preferences: ^2.2.2 
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any
  cupertino_icons: ^1.0.8
  connectivity_plus: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/light-background.png
    - assets/dark-background.png

