// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZkW-A3xpmiz7sc0UlkBf16VDz53ffpag',
    appId: '1:765152134631:web:b72f8017679e5c5dc6a942',
    messagingSenderId: '765152134631',
    projectId: 'colormemorizer',
    authDomain: 'colormemorizer.firebaseapp.com',
    storageBucket: 'colormemorizer.firebasestorage.app',
    measurementId: 'G-1TF4RQ4SGP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDibZ-q4dxaCJS-YU4fwUzeXUez7bZvNW8',
    appId: '1:765152134631:android:fe90ad2393f91a74c6a942',
    messagingSenderId: '765152134631',
    projectId: 'colormemorizer',
    storageBucket: 'colormemorizer.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxYnq20GEiKTyP-mm2NdNeF7oRNDEjc58',
    appId: '1:765152134631:ios:cc10e11da8355307c6a942',
    messagingSenderId: '765152134631',
    projectId: 'colormemorizer',
    storageBucket: 'colormemorizer.firebasestorage.app',
    iosBundleId: 'com.example.colorMemorizer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDxYnq20GEiKTyP-mm2NdNeF7oRNDEjc58',
    appId: '1:765152134631:ios:cc10e11da8355307c6a942',
    messagingSenderId: '765152134631',
    projectId: 'colormemorizer',
    storageBucket: 'colormemorizer.firebasestorage.app',
    iosBundleId: 'com.example.colorMemorizer',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAZkW-A3xpmiz7sc0UlkBf16VDz53ffpag',
    appId: '1:765152134631:web:ab79391248e75b76c6a942',
    messagingSenderId: '765152134631',
    projectId: 'colormemorizer',
    authDomain: 'colormemorizer.firebaseapp.com',
    storageBucket: 'colormemorizer.firebasestorage.app',
    measurementId: 'G-JPCK56VC6M',
  );
}
